name: j_courier
description: "Application for courier"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  dio: ^5.6.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  talker_flutter: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_bloc_logger: ^4.4.1
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  auto_route: ^9.2.2
  flutter_svg: ^2.0.10
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  auto_route_generator: ^9.0.0
  build_runner:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
  

flutter_intl:
  enabled: true
