name: j_courier
description: "Application for courier"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  dio: ^5.6.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  talker_flutter: ^4.6.5
  talker_dio_logger: ^4.6.5
  talker_bloc_logger: ^4.6.5
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  auto_route: ^9.2.2
  flutter_svg: ^2.0.10
  mask_text_input_formatter: ^2.9.0
  local_auth: ^2.3.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  go_router: ^7.0.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  auto_route_generator: ^9.0.0
  build_runner:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
    - assets/svg/tabs/
    - assets/svg/settings/

flutter_intl:
  enabled: true
